# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pid',
        ),
        migrations.AddField(
            model_name='blog',
            name='default',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
