# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-12 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_auto_20170711_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='Set Name', max_length=25),
        ),
        migrations.AlterField(
            model_name='blog',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
